### 测试用户登录接口
POST http://127.0.0.1:8081/api/v1/users/login
Content-Type: application/json

{
  "loginAccount": "admin_teacher",
  "password": "123"
}

### 测试注册接口
POST http://127.0.0.1:8081/api/v1/users/register
Content-Type: application/json

{
  "loginAccount": "admin_teacher",
  "password": "123",
  "role": "teacher"
}

### 测试看板统计接口
GET http://127.0.0.1:8081/api/v1/dashboard/stats
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3MzgxNTU2NiwiZXhwIjoxNzczOTAxOTY2fQ.-oa4NphhCDe0O9fTqQ73PhQuW-NT5y_Jstfvq-R6LLM

### 测试看板统计接口
GET http://127.0.0.1:8081/api/v1/dashboard/class-progress
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3MzgxNTU2NiwiZXhwIjoxNzczOTAxOTY2fQ.-oa4NphhCDe0O9fTqQ73PhQuW-NT5y_Jstfvq-R6LLM

### 测试学生列表接口
GET http://localhost:8081/api/v1/students
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3MzkxMTM5MCwiZXhwIjoxNzczOTk3NzkwfQ.-tI3msVPL0K--fWutErE1VNvKzvx3wBkMOpyPApfQ0A


### 测试布置作业
POST http://localhost:8081/api/v1/assignments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3MzkxNDc2MSwiZXhwIjoxNzc0MDAxMTYxfQ.fb9OwHyL0lfN7jD1eq75vaUB2rJBuZfaFRa1ditym84

{
  "classIds": [
    "class-test-01",
    "class-test-02"
  ],
  "title": "春季核心词汇突击测试",
  "targetGrade": "高一核心词汇",
  "deadline": "2026-03-20T23:59:59",
  "baseWordIds": [
    "word-test-01",
    "word-test-02",
    "word-test-03"
  ],
  "isPersonalized": true
}

### 测试班级
GET http://localhost:8081/api/v1/assignments/options
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3NDA4NjY3MSwiZXhwIjoxNzc0MTczMDcxfQ.GXAnrXRrtqh6SSACmumg_qXoZEds-jtVTu76K-mWGO0

### 获取词书
GET http://localhost:8081/api/v1/wordbooks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3NDI3NDE4MywiZXhwIjoxNzc0MzYwNTgzfQ.R9NWlC2HjgktuwiMxW0NTkOa1mAL9G9LUKMlyVRKTjw

### 获取单词
GET http://localhost:8081/api/v1/vocabularies?bookId=book-test-01
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbkFjY291bnQiOiJhZG1pbl90ZWFjaGVyIiwicm9sZSI6InRlYWNoZXIiLCJpZCI6IjFkMTE2ZDE4LTExNDgtNDFiMS05NmE3LTM5MTEyMWQwMDc0MyIsImlhdCI6MTc3NDI3NDE4MywiZXhwIjoxNzc0MzYwNTgzfQ.R9NWlC2HjgktuwiMxW0NTkOa1mAL9G9LUKMlyVRKTjw